"""Add notification_settings to dinas

Revision ID: 01d413954192
Revises: a77073a70047
Create Date: 2026-01-28 21:34:13.015382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d413954192'
down_revision = 'a77073a70047'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dinas', sa.Column('notification_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dinas', 'notification_settings')
    # ### end Alembic commands ###
