"""Initial migration

Revision ID: a77073a70047
Revises: None
Create Date: 2026-01-28 19:15:32.844153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77073a70047'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dinas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kabupaten', sa.String(length=100), nullable=False),
    sa.Column('provinsi', sa.String(length=100), nullable=False),
    sa.Column('alamat', sa.String(length=500), nullable=False),
    sa.Column('telepon', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo_dinas', sa.String(length=255), nullable=True),
    sa.Column('logo_kabupaten', sa.String(length=255), nullable=True),
    sa.Column('kepala_dinas', sa.String(length=255), nullable=False),
    sa.Column('nip_kepala_dinas', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dinas_id'), 'dinas', ['id'], unique=False)
    op.create_table('jalur',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('persyaratan', sa.JSON(), nullable=True),
    sa.Column('berkas_wajib', sa.JSON(), nullable=True),
    sa.Column('radius_zonasi', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jalur_id'), 'jalur', ['id'], unique=False)
    op.create_table('tahun_ajaran',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tahun', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tanggal_mulai_pendaftaran', sa.DateTime(), nullable=False),
    sa.Column('tanggal_akhir_pendaftaran', sa.DateTime(), nullable=False),
    sa.Column('tanggal_seleksi', sa.DateTime(), nullable=False),
    sa.Column('tanggal_pengumuman', sa.DateTime(), nullable=False),
    sa.Column('tanggal_daftar_ulang', sa.DateTime(), nullable=False),
    sa.Column('tanggal_akhir_daftar_ulang', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tahun_ajaran_id'), 'tahun_ajaran', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'admin_dinas', 'admin_sekolah', 'siswa', name='userrole'), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('sekolah',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dinas_id', sa.String(length=36), nullable=False),
    sa.Column('npsn', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('jenjang', sa.Enum('SD', 'SMP', name='jenjang'), nullable=False),
    sa.Column('alamat', sa.String(length=500), nullable=False),
    sa.Column('kelurahan', sa.String(length=100), nullable=False),
    sa.Column('kecamatan', sa.String(length=100), nullable=False),
    sa.Column('telepon', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('kepala_sekolah', sa.String(length=255), nullable=False),
    sa.Column('nip_kepala_sekolah', sa.String(length=50), nullable=False),
    sa.Column('ketua_spmb', sa.String(length=255), nullable=False),
    sa.Column('akreditasi', sa.String(length=5), nullable=True),
    sa.Column('status', sa.Enum('negeri', 'swasta', name='status_sekolah'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dinas_id'], ['dinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sekolah_id'), 'sekolah', ['id'], unique=False)
    op.create_index(op.f('ix_sekolah_npsn'), 'sekolah', ['npsn'], unique=True)
    op.create_table('siswa',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('nisn', sa.String(length=20), nullable=False),
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=255), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=100), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=1), nullable=False),
    sa.Column('agama', sa.String(length=20), nullable=False),
    sa.Column('alamat', sa.String(length=500), nullable=False),
    sa.Column('rt', sa.String(length=5), nullable=True),
    sa.Column('rw', sa.String(length=5), nullable=True),
    sa.Column('kelurahan', sa.String(length=100), nullable=False),
    sa.Column('kecamatan', sa.String(length=100), nullable=False),
    sa.Column('kabupaten', sa.String(length=100), nullable=False),
    sa.Column('provinsi', sa.String(length=100), nullable=False),
    sa.Column('kode_pos', sa.String(length=10), nullable=True),
    sa.Column('koordinat_rumah', sa.JSON(), nullable=True),
    sa.Column('telepon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('asal_sekolah', sa.String(length=255), nullable=True),
    sa.Column('npsn_asal_sekolah', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_siswa_id'), 'siswa', ['id'], unique=False)
    op.create_index(op.f('ix_siswa_nik'), 'siswa', ['nik'], unique=True)
    op.create_index(op.f('ix_siswa_nisn'), 'siswa', ['nisn'], unique=True)
    op.create_table('berita',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dinas_id', sa.String(length=36), nullable=True),
    sa.Column('sekolah_id', sa.String(length=36), nullable=True),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('ringkasan', sa.Text(), nullable=True),
    sa.Column('isi', sa.Text(), nullable=False),
    sa.Column('gambar', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dinas_id'], ['dinas.id'], ),
    sa.ForeignKeyConstraint(['sekolah_id'], ['sekolah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_berita_id'), 'berita', ['id'], unique=False)
    op.create_index(op.f('ix_berita_slug'), 'berita', ['slug'], unique=True)
    op.create_table('kuota',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sekolah_id', sa.String(length=36), nullable=False),
    sa.Column('jalur_id', sa.String(length=36), nullable=False),
    sa.Column('tahun_ajaran', sa.String(length=20), nullable=False),
    sa.Column('kuota', sa.Integer(), nullable=False),
    sa.Column('terisi', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jalur_id'], ['jalur.id'], ),
    sa.ForeignKeyConstraint(['sekolah_id'], ['sekolah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kuota_id'), 'kuota', ['id'], unique=False)
    op.create_table('pendaftaran',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('siswa_id', sa.String(length=36), nullable=False),
    sa.Column('sekolah_id', sa.String(length=36), nullable=False),
    sa.Column('jalur_id', sa.String(length=36), nullable=False),
    sa.Column('tahun_ajaran_id', sa.String(length=36), nullable=False),
    sa.Column('no_pendaftaran', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('jarak_ke_sekolah', sa.Float(), nullable=True),
    sa.Column('nilai_rata', sa.Float(), nullable=True),
    sa.Column('skor_zonasi', sa.Float(), nullable=True),
    sa.Column('skor_prestasi', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['jalur_id'], ['jalur.id'], ),
    sa.ForeignKeyConstraint(['sekolah_id'], ['sekolah.id'], ),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa.id'], ),
    sa.ForeignKeyConstraint(['tahun_ajaran_id'], ['tahun_ajaran.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pendaftaran_id'), 'pendaftaran', ['id'], unique=False)
    op.create_index(op.f('ix_pendaftaran_no_pendaftaran'), 'pendaftaran', ['no_pendaftaran'], unique=True)
    op.create_table('pengumuman',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dinas_id', sa.String(length=36), nullable=True),
    sa.Column('sekolah_id', sa.String(length=36), nullable=True),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('isi', sa.Text(), nullable=False),
    sa.Column('tipe', sa.String(length=20), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dinas_id'], ['dinas.id'], ),
    sa.ForeignKeyConstraint(['sekolah_id'], ['sekolah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pengumuman_id'), 'pengumuman', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pengumuman_id'), table_name='pengumuman')
    op.drop_table('pengumuman')
    op.drop_index(op.f('ix_pendaftaran_no_pendaftaran'), table_name='pendaftaran')
    op.drop_index(op.f('ix_pendaftaran_id'), table_name='pendaftaran')
    op.drop_table('pendaftaran')
    op.drop_index(op.f('ix_kuota_id'), table_name='kuota')
    op.drop_table('kuota')
    op.drop_index(op.f('ix_berita_slug'), table_name='berita')
    op.drop_index(op.f('ix_berita_id'), table_name='berita')
    op.drop_table('berita')
    op.drop_index(op.f('ix_siswa_nisn'), table_name='siswa')
    op.drop_index(op.f('ix_siswa_nik'), table_name='siswa')
    op.drop_index(op.f('ix_siswa_id'), table_name='siswa')
    op.drop_table('siswa')
    op.drop_index(op.f('ix_sekolah_npsn'), table_name='sekolah')
    op.drop_index(op.f('ix_sekolah_id'), table_name='sekolah')
    op.drop_table('sekolah')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tahun_ajaran_id'), table_name='tahun_ajaran')
    op.drop_table('tahun_ajaran')
    op.drop_index(op.f('ix_jalur_id'), table_name='jalur')
    op.drop_table('jalur')
    op.drop_index(op.f('ix_dinas_id'), table_name='dinas')
    op.drop_table('dinas')
    # ### end Alembic commands ###
