"""add_signature_url_to_dinas

Revision ID: e374ae05b4fc
Revises: 01d413954192
Create Date: 2026-01-28 21:47:47.336787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e374ae05b4fc'
down_revision = '01d413954192'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dinas', sa.Column('signature_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dinas', 'signature_url')
    # ### end Alembic commands ###
