"""Add dinas_id and sekolah_id to users

Revision ID: edc49cd42e58
Revises: e374ae05b4fc
Create Date: 2026-01-28 22:42:48.141781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc49cd42e58'
down_revision = 'e374ae05b4fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dinas_id', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('sekolah_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sekolah_id')
    op.drop_column('users', 'dinas_id')
    # ### end Alembic commands ###
